export const info = [
  {
    title: 'Short Hike',
    comment: 'See that mountain? You can climb it!',
  },
  {
    title: 'Painting the Fence',
    comment: 'Only if it ain’t raining',
  },
  {
    title: 'Dog Show',
    comment: 'Or are they... tortoises?',
  },
  {
    title: 'Chess Tournament',
    comment: 'e2 e4',
  },
  {
    title: 'Shady Business',
    comment: '',
  },
  {
    title: 'Test Event',
    comment: 'It’s a demo after all. What did you expect?',
  },
];

export const locations = [
  'Hong Kong',
  'Bangkok',
  'London',
  'Macau',
  'Singapore',
  'Paris',
  'Dubai',
  'New York City',
  'Kuala Lumpur',
  'Istanbul',
  'Delhi',
  'Antalya',
  'Shenzhen',
  'Mumbai',
  'Phuket',
  'Rome',
  'Tokyo',
  'Pattaya',
  'Taipei',
  'Mecca',
  'Guangzhou',
  'Prague',
  'Medina',
  'Seoul',
  'Amsterdam',
  'Agra',
  'Miami',
  'Osaka',
  'Las Vegas',
  'Shanghai',
  'Ho Chi Minh City',
  'Denpasar',
  'Barcelona',
  'Los Angeles',
  'Milan',
  'Chennai',
  'Vienna',
  'Johor Bahru',
  'Jaipur',
  'Cancun',
  'Berlin',
  'Cairo',
  'Orlando',
  'Moscow',
  'Venice',
  'Madrid',
  'Ha Long',
  'Riyadh',
  'Dublin',
];
